# Generated by Django 3.2.8 on 2021-10-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_actor_movies',
            old_name='actor_id',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='movie_actor_movies',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movies_review',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
